// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro();
  autoresForm: string = '';
  editoras: Editora[] = [];

  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService, private router: Router) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
}

<main role="main" class="container">
    <h1>Cadastrar Livro</h1>

    <form (submit)="incluir()" ngNativeValidate>
        <div class="form-group">
            <label for="titulo">Título:</label>
            <input type="text" class="form-control" id="titulo" name="titulo" required [(ngModel)]="livro.titulo">
        </div>
        <div class="form-group">
            <label for="resumo">Resumo:</label>
            <textarea class="form-control" id="resumo" name="resumo" rows="3" [(ngModel)]="livro.resumo"></textarea>
        </div>
        <div class="form-group">
            <label for="editora">Editora:</label>
            <select class="form-control" id="editora" name="editora" required [(ngModel)]="livro.codEditora">
                <option value="" disabled selected>Selecione uma editora</option>
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
            </select>
        </div>
        <div class="form-group">
            <label for="autores">Autores:</label>
            <textarea class="form-control" id="autores" name="autores" rows="3" [(ngModel)]="autoresForm"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</main>

// clientes/livros-next/pages/LivroDados.tsx
import type { NextPage } from 'next'
import React from 'react'
const LivroDados: NextPage = () => { return (<main>ol==ola mundo</main>) }

import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { ControleLivros } from '../classes/controle/ControleLivros';

const controleLivros = new ControleLivros();

export default function LivroDados() {
    const navigate = useNavigate();
    const [opcoes, setOpcoes] = useState([]);
    const [titulo, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [codEditora, setCodEditora] = useState('');

    useEffect(() => {
        const fetchEditoras = async () => {
            const editoras = await controleLivros.getEditoras();
            setOpcoes(editoras.map(editora => ({
                value: editora.codEditora,
                text: editora.nome
            })));
        };
        fetchEditoras();
    }, []);

    const tratarCombo = (event) => {
        const { value } = event.target;
        setCodEditora(value);
    };

    const incluir = async (event) => {
        event.preventDefault();
        const livro = {
            codigo: 0,
            codEditora: parseInt(codEditora),
            titulo,
            resumo,
            autores: autores.split('\n')
        };
        await controleLivros.incluir(livro);
        navigate('/');
    };

    return (
        <div className="container">
            <h1>Dados do Livro</h1>
            <form onSubmit={incluir}>
                <label>
                    Título:
                    <input type="text" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
                </label>
                <label>
                    Resumo:
                    <textarea value={resumo} onChange={(e) => setResumo(e.target.value)} />
                </label>
                <label>
                    Editora:
                    <select value={codEditora} onChange={tratarCombo}>
                        {opcoes.map(opcao => (
                            <option key={opcao.value} value={opcao.value}>{opcao.text}</option>
                        ))}
                    </select>
                </label>
                <label>
                    Autores:
                    <textarea value={autores} onChange={(e) => setAutores(e.target.value)} />
                </label>
                <button type="submit">Salvar Dados</button>
            </form>
        </div>
    );
}
